IsaacThawer/BankruptcySolutions

- Homepage.html
#JIRA 21
#This features an overview of Our Services on the Homepage
> Update to Services (3)

- .vscode/settings.json
- about-us.html
- reviews.html
> #Jira SCRUM-46

- .vscode/launch.json
- Homepage.html
- styles.css
> #JIRA 18,51, 52

- Homepage.html
Alexis forgot to post the pull request, so I'm doing it
> added initial HTML code and styling for testimonials GOOGLE/YELP

- services.html
#Create code base for services page
> #Jira SCRUM-85

- Homepage.html
- css/styles.css
- Replaced Chapter 15 bankruptcy with Chapter 11 and 12 bankruptcy services
- Reordered services to logical sequence: Chapter 7, 11, 12, 13
- Converted inline styles to proper CSS classes in stylesheet
- Used blue color (#147dd3) for all headings
- Updated the header fonts
- Created a grid layout for services and added proper spacing and alignment to match Figma
> Scrum-74: Changes to Services

- reviews.html
- services.html
updated navbar to all existing pages, while adding placeholders for reviews and services page
> scrum-81,87 

- Homepage.html
- css/styles.css
- The client wanted to add a link to bankruptcy matters ( a link that describes the process of Bankruptcy that's from a public domain)
- The link was added under the Services section
> SCRUM #76- Adding Link/Information regarding Bankruptcy Process

- about-us.html
- index.html
- reviews.html
- services.html
I refactored the name of Homepage.html to index.html. I then changed the links in the navbar to preserve functionality and changed the title to meet client requirements.
> #SCRUM #72,75

- css/styles.css
- login.html
I Created the basic UI design for the login page. The login process is not functional for now, only the visual makeup.
> SCRUM-98: Creating Login Page UI

- index.html
Link Google and Yelp to client review page
> SCUM-#96: Link Google and Yelp to client review page

- README.md
scrum-108, updated README file
> scrum-108, updated README file

- README.md
such as testing, deployment, timeline, developer instructions, and adding to the known issues
> Added material for the assignment specific material

- public/reviews.html
SCRUM-121: Add background hover color to all pages of the Nav Bar
SCRUM-130: Change the photo on the reviews page
SCRUM-109: Update website file system to have /public and /admin folders
SCRUM-111: Change stylesheet location for Login.html
> These are the tasks with acceptance to criteria.

- admin/dashboard.html
- admin/js/dashboard.js
Added function in dashboard.js which shows the date and time on the dashboard. Note I had to change the script tag paths in the dashboard.html file from admin/js/dashboard.html to js/dashboard.html.
> SCRUM 127--Adjust the timer to keep current time on Admin Dashboard

- server.js
Mainly changed the login url to admin-login, but also added some dummy auth for future cases where u will only be able to access admin/dashboard.html if you are admin, just to get out for now. need to comment out line 11 for that code to work.
> SCRUM-37 Admin login page is accessed via a separate URL

- admin/js/auth.js
this is the feature to add/remove permission for users. There were issues in enabling this feature and will require to be worked on more
> scrum-77 Add/remove permissions for users

- public/css/styles.css
- public/index.html
- public/js/form-handler.js
- server.js
From the Homepage, when using the Client information submission form, the data is able to be sent and stored into DynamoDB
- Users can enter and submit client information through the form.
- If validation fails, the user receives appropriate error messages.
- If validation succeeds, the data is successfully sent to DynamoDB.
- The system confirms successful data storage in DynamoDB.
- If there is an error in data submission, an error message is displayed to the user.
- Submitted data is properly structured and stored in DynamoDB as per the defined schema.
> SCRUM 144: Client information sent to DynamoDB

- admin/client_submissions.html
- admin/dashboard.html
Sign out buttons now both redirect to index.html
> page redirection on sign out for client submission and dashboard

- .gitignore
- admin/client_submissions.html
- admin/css/style.css
- admin/js/client_submissions.js
- how-to-run.txt
- server.js
- server.js file updated to use .env for Access Key and Secret Key.
- Instructions for running server.js with .env added to the how-to-run.txt file.
- client_submissions.html converted to JavaScript, and client_submissions.js created with the Clients column code moved into it.
- Style file modified and adjusted for copyright footer and active client selection.
- Read, Delete, and Modify functions added to client_submissions.js to enable button functionalities.
-Code added to server.js to Read, Delete, and Modify data in DynamoDB.
> SCRUM #146: Pull information from DynamoDB to the database page

- admin/css/dashboard-styles.css
Styling is now correct for date and time on admin dashboard
> small bug fix involving the date and time styling

- admin/js/dashboard.js
- how-to-run.txt
- server.js
Functionality to load users into the table works within the dashboard, however the api call to delete and add users still warrants further testing. The permissions may need to be adjusted to allow for the api call on AWS API Gateway
> Functionality to load users into the table works within the dashboard

- admin/js/client_submissions.js
Formated the timestamps retrieved from DynamoDB which were previously displayed as ISO-8601 format (e.g., "2025-02-20T15:15:00Z"), is now converted to a more readable format like "MM/DD/YYYY HH:MM AM/PM" for better user experience.
> SCRUM 167- Format DynamoDB ISO Timestamps to User-Friendly Display

- public/css/styles.css
> # SCRUM-180

- admin/client_submissions.html
- admin/dashboard.html
- admin/js/db-status.js
had a bug where the db-indicator was not formatted correctly in the db page. Removed the indicator from the db page since it is redundant, and moved the indicator in the dashboard
> SCRUM-198 fix bug, moved indicator to admin dashboard

- public/css/styles.css
> #SCRUM-201

- admin/js/client_submissions.js
bug fix- search not working in client submission fixed
> Bug fix- search not working on client submission fixed

- README.md
- public/index.html
> # SCRUM-203, 211

- admin/content/index-map.json
- admin/css/style.css
- admin/js/auth.js
- admin/js/dashboard.js
- admin/js/read-script.js
- public/index.html
- public/js/google-map.js
> #SCRUM-205,212

- admin/js/reviews.js
- public/js/reviews-loader.js
- test/reviews-loader.test.js
- test/reviews.test.js
Implemented Jest testing for the reviews Page and Reviews Admin control to ensure reliability This includes both the public-facing reviews page and the admin dashboard for managing reviews.
> SCRUM 216- Unit Test - Reviews Management System

- test/auth.frontend.test.js
added jsdom testing for auth.js
> SCRUM-227 authentication and token handling

- test/client-form-validation.test.js
Conducted functional testing to verify that the client submission form How Can We Help? Field enforces the correct character limits as defined in validation rules. This ensures users cannot input more characters than allowed and that appropriate feedback or error messages are displayed when limits are exceeded.
> SCRUM 219: Form Field Validation – Character Limits Functional Test

- admin/css/dashboard-styles.css
- admin/js/dashboard.js
- public/js/menu-toggle.js
- test/mobNav.test.js
- test/showTime.test.js
- test/signOutButton.test.js
functional tests for the mobile navbar, Date and time function, and Sign out and redirect buttons.
as well as fixed some mobile optimization bugs
> Scrum 225,226,228,229

- test/admin-navigation.test.js
- test/client-form-validation.test.js
Perform a functional test to verify that all sections of the admin panel can be accessed and navigated without issues. This ensures that all navigation links, menus, and routing within the admin interface work as intended, and users can move smoothly between different sections of the panel.
> SCRUM 222: Functional Test – Admin Panel Navigation

- test/auth.test.js
> #SCRUM-217

- admin/js/auth.js
- test/auth.test.js
unit testing on auth.js
- fix error checks on auth.js
- added more tests to get to 85% coverage on auth.test.js
> SCRUM 241: unit testing for auth.test.js

- admin/js/profilePhoto.js
- test/profilePhoto.test.js
- updated profilePhoto.js with better updates to handle errors, readability, and testing
- add a new profilePhoto.test.js for testing
> scrum248: profilePhoto.js testing

- test/form-handler.test.js
Unit Test - Get the test coverage to 85% or more for form-handler.js
> SCRUM 242: Form Handler Unit Test

- test/menu-toggle.test.js
menu-toggle test for maximum coverage
> JIRA SCRUM #246 menu-toggle test with maximum coverage

- admin/content/index-title.json
- admin/js/dashboard.js
- admin/js/upload-image.js
- test/dashboard.test.js
- test/user-management.test.js
Unit testing for Dashboard.js,  did a little bit of reorganization of the dashboard.js to be able to export update Contemt function
> SCRUM-243-Dashboard.js unit testing

- public/js/fade-in.js
- public/js/google-map.js
- server.js
- test/fade-in.test.js
- test/google-map.test.js
#238-fixed bug for valid recaptcha verification in server.js #240-added unit testing for google-map.js to meet the standard of minimum 85% coverage #247-added unit testing for fade-in.js to meet the standard of minimum 85% coverage
> #JIRA-238,240,247
